### ISSUE TITLE
ARYA electrum servers?

### ISSUE THREAD

**Issue by smk762** [Aryacoin/Aryacoin#4]
We're wanting to add ARYA to the https://atomicdex.io/en/ wallet, but to do so we need to know the details for your electrum servers to make it work. If you don't have electrum servers setup, we can walk you through it, or point you to a reliable 3rd party offering to maintain them as a service.
If you want to discuss, you can find me on the [KomodoPlatform Discord](https://komodoplatform.com/discord), or you can open a PR in https://github.com/KomodoPlatform/coins

**Comment by sillyghost** [comment]
Closing this issue as the servers were added.
